-- ============================================================
-- ARCHIVO OBSOLETO — ver mga-master-schema.sql
-- Este archivo fue reemplazado por mga-master-schema.sql
-- que contiene el esquema master completo con todos los campos
-- comerciales y políticas RLS.
-- ============================================================
