-- Permite insertar un id explícito en proveedores (necesario para importación)
-- GENERATED ALWAYS bloquea cualquier INSERT con id; BY DEFAULT lo permite.
ALTER TABLE public.proveedores
  ALTER COLUMN id SET GENERATED BY DEFAULT;
